import type { Metadata } from "next";
import { LegalPage } from "../../components/propfund/LegalPage";

export const metadata: Metadata = {
  title: "Privacy policy | Propfund",
  description: "How Propfund collects, uses, and protects personal information.",
};

const sections = [
  {
    title: "Scope",
    paragraphs: ["This policy explains how Propfund collects, uses, shares, and protects personal information when you visit our website, request access, purchase an evaluation, or use a simulated trading account."],
  },
  {
    title: "Information we collect",
    paragraphs: ["We collect information you provide directly, information generated by your use of the service, and limited technical information from your device."],
    bullets: ["Identity and contact details, including name and email address.", "Account, market, evaluation, payment, and support information.", "Trading activity, rule checks, device identifiers, browser data, IP address, and service logs.", "Cookie and analytics data used to understand performance and improve the site."],
  },
  {
    title: "How we use information",
    paragraphs: ["We use personal information to provide and secure the service, administer evaluations, communicate with you, process payments and eligible rewards, investigate misuse, comply with law, and improve Propfund."],
  },
  {
    title: "When we share information",
    paragraphs: ["We may share information with vendors that help us operate payment, identity, infrastructure, analytics, communications, support, and simulated trading services. They may use the information only for the work they perform for us. We may also disclose information to comply with law, protect users, investigate fraud, or complete a corporate transaction."],
  },
  {
    title: "Cookies and analytics",
    paragraphs: ["We may use essential cookies for security and service operation, plus analytics technologies that help us measure usage. Browser settings can limit some cookies, although parts of the service may not work correctly without essential storage."],
  },
  {
    title: "Retention and security",
    paragraphs: ["We keep information only as long as needed for the purposes described here, including legal, accounting, fraud-prevention, and dispute requirements. We use administrative, technical, and organizational safeguards, but no online system can guarantee absolute security."],
  },
  {
    title: "Your choices and rights",
    paragraphs: ["Depending on where you live, you may have rights to access, correct, delete, restrict, or obtain a copy of your information, and to object to certain processing. We may need to verify your identity before completing a request."],
  },
  {
    title: "International use and children",
    paragraphs: ["Information may be processed in countries other than the one where you live. Propfund is not intended for children, and we do not knowingly collect personal information from anyone under the minimum legal age required to use the service."],
  },
  {
    title: "Updates and contact",
    paragraphs: ["We may update this policy as the service or law changes. The effective date above shows the latest revision. Questions and privacy requests can be sent to support@propfund.com."],
  },
];

export default function PrivacyPolicyPage() {
  return <LegalPage title="Privacy policy" intro="What we collect, why we use it, and the choices you have." sections={sections} />;
}
