/**
 * Data for the Transparency page (PRD §11).
 *
 * Build mode: `getTransparencyData()` returns a deterministic SAMPLE dataset.
 * It is generated by simulating individual accounts through the real rules
 * (packages and fees from site-data, pass → funded, payouts at 80% of profit
 * paid 7 days after the request, rebuys after a breach), so every figure is
 * consistent with every other one. The page must label it "Sample data".
 *
 * When live figures exist, replace `getTransparencyData()` with a fetch that
 * returns the same `TransparencyData` shape and `mode: "live"`.
 */
import { challengePackages, PAYOUT_REVIEW_DAYS, MIN_PAYOUT_USD, TRADER_SPLIT_PCT } from "./site-data";

export const ASSET_CLASSES = ["Forex", "Crypto", "Equities", "Commodities"] as const;
export type AssetClass = (typeof ASSET_CLASSES)[number];

export type TransparencyPackage = { id: string; name: string; label: string };

export type TransparencyPayout = {
  id: string;
  /** ISO date (YYYY-MM-DD) the request was submitted. */
  requestedOn: string;
  /** ISO date (YYYY-MM-DD) the payout was sent. */
  paidOn: string;
  /** Anonymized trader ID, e.g. "T-4F2A". Never a name or email. */
  traderId: string;
  /** Realized profit debited from the account. */
  profit: number;
  /** Amount paid to the trader in USDC (80% of profit). */
  amount: number;
  hoursToPay: number;
  /** Arbitrum transaction hash. Null in sample data. */
  txHash: string | null;
};

export type TransparencySeries = {
  /** Traders with an open challenge or funded account that day. */
  activeTraders: number[];
  /** Traders who have paid for at least one challenge, cumulative. */
  payingTraders: number[];
  /** Daily fee revenue by package id. */
  revenueByPackage: Record<string, number[]>;
  revenueDaily: number[];
  revenueCumulative: number[];
  /** Daily challenge purchases by package id. */
  purchasesByPackage: Record<string, number[]>;
  /** Cumulative passes ÷ cumulative resolved challenges, 0–1. Null until enough challenges have resolved. */
  passRate: (number | null)[];
  breachesDaily: number[];
  breachesMax: number[];
  notionalVolume: number[];
  tradeCount: number[];
  volumeByAssetClass: Record<AssetClass, number[]>;
  fundedTraders: number[];
  fundedCapital: number[];
  payoutsDaily: number[];
  payoutsCumulative: number[];
  hedgingRealizedCumulative: number[];
  hedgingUnrealized: number[];
};

export type TransparencyStats = {
  feeRevenueLifetime: number;
  /** Last 30 complete days of fee revenue × 365 / 30. */
  annualizedRunRate: number;
  totalPayouts: number;
  payoutCount: number;
  largestPayout: number;
  medianHoursToPay: number;
  activeTraders30d: number;
  payingTraders: number;
  fundedTraders: number;
  fundedCapital: number;
  passRate: number;
  passes: number;
  resolvedChallenges: number;
  challengesSold: number;
  /** totalPayouts ÷ feeRevenueLifetime. */
  payoutsShareOfRevenue: number;
  hedgingRealized: number;
  hedgingUnrealized: number;
  /** hedgingRealized ÷ totalPayouts. */
  hedgingCoverage: number;
};

export type TransparencyData = {
  mode: "sample" | "live";
  /** Last complete day in the dataset (YYYY-MM-DD, UTC). Today is excluded. */
  asOf: string;
  dates: string[];
  packages: TransparencyPackage[];
  series: TransparencySeries;
  stats: TransparencyStats;
  /** Most recent paid payouts, newest first. */
  recentPayouts: TransparencyPayout[];
};

/* ------------------------------------------------------------------ */
/* Deterministic randomness                                           */
/* ------------------------------------------------------------------ */

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

type Rng = ReturnType<typeof mulberry32>;

const uniform = (rng: Rng, min: number, max: number) => min + (max - min) * rng();

function gaussian(rng: Rng): number {
  const u = Math.max(rng(), 1e-12);
  const v = rng();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function poisson(rng: Rng, lambda: number): number {
  if (lambda > 30) return Math.max(0, Math.round(lambda + Math.sqrt(lambda) * gaussian(rng)));
  const limit = Math.exp(-lambda);
  let k = 0;
  let p = 1;
  do {
    k += 1;
    p *= rng();
  } while (p > limit);
  return k - 1;
}

/** Number of trials until the first success, ≥ 1. */
function geometric(rng: Rng, p: number): number {
  return Math.max(1, Math.ceil(Math.log(1 - rng()) / Math.log(1 - p)));
}

function pickWeighted(rng: Rng, weights: number[]): number {
  const total = weights.reduce((sum, w) => sum + w, 0);
  let roll = rng() * total;
  for (let i = 0; i < weights.length; i += 1) {
    roll -= weights[i];
    if (roll < 0) return i;
  }
  return weights.length - 1;
}

/* ------------------------------------------------------------------ */
/* Dates                                                              */
/* ------------------------------------------------------------------ */

const DAY_MS = 86_400_000;

function isoDate(ms: number): string {
  return new Date(ms).toISOString().slice(0, 10);
}

function median(values: number[]): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

const round2 = (value: number) => Math.round(value * 100) / 100;

function cumulative(values: number[]): number[] {
  let running = 0;
  return values.map((value) => {
    running += value;
    return round2(running);
  });
}

function runningFromDiff(diff: number[]): number[] {
  let running = 0;
  return diff.map((value) => {
    running += value;
    return running;
  });
}

/* ------------------------------------------------------------------ */
/* Sample model                                                       */
/* ------------------------------------------------------------------ */

/**
 * How big the sample business is. Every figure scales together: the only knob
 * is how many new paying traders arrive each day, and the model derives
 * purchases, fees, breaches, funded capital and payouts from that.
 */
export type TransparencyScale = "small" | "medium" | "mega";

export const TRANSPARENCY_SCALES: { id: TransparencyScale; label: string; description: string }[] = [
  { id: "small", label: "Limited users", description: "Early days: a few hundred paying traders" },
  { id: "medium", label: "Many users", description: "The default sample: thousands of traders" },
  { id: "mega", label: "Mega user base", description: "At scale: tens of thousands of traders" },
];

/** Multiplier on daily new traders. `medium` is 1, so it is the default dataset. */
const SCALE_FACTOR: Record<TransparencyScale, number> = { small: 0.07, medium: 1, mega: 8 };

export function isTransparencyScale(value: unknown): value is TransparencyScale {
  return value === "small" || value === "medium" || value === "mega";
}

/** Read a `?scale=` param. Anything else (including absent) falls back to the default. */
export function parseTransparencyScale(value: unknown): TransparencyScale | null {
  const raw = Array.isArray(value) ? value[0] : value;
  return isTransparencyScale(raw) ? raw : null;
}

export type SampleOptions = { asOf?: string; days?: number; seed?: number; scale?: TransparencyScale };

/** Sample model assumptions. Plausible for a one-step challenge, not real figures. */
const MODEL = {
  packageWeights: [0.3, 0.28, 0.22, 0.13, 0.07],
  newTradersStart: 14,
  newTradersEnd: 66,
  meanChallengeDays: 11,
  passProbability: 0.12,
  dailyBreachShare: 0.58,
  challengeRebuyProbability: 0.34,
  fundedRebuyProbability: 0.3,
  fundedDailyBreachProbability: 0.013,
  meanDaysBetweenPayouts: 14,
  payoutRequestProbability: 0.62,
  payoutProfitRange: [0.004, 0.032] as const,
  /** A few strong months: some requests land well above the usual range. */
  largePayoutProbability: 0.04,
  largePayoutProfitRange: [0.032, 0.075] as const,
  minResolvedForPassRate: 25,
  voidedProbability: 0.015,
} as const;

type Payout = TransparencyPayout & { requestDay: number; paidDay: number; cents: number; voided: boolean };

export function buildSampleTransparencyData({
  asOf = "2026-09-14",
  days = 240,
  seed = 0x50f0d,
  scale = "medium",
}: SampleOptions = {}): TransparencyData {
  const rng = mulberry32(seed);
  const factor = SCALE_FACTOR[scale];
  const newTradersStart = MODEL.newTradersStart * factor;
  const newTradersEnd = MODEL.newTradersEnd * factor;
  // Anonymized IDs must stay unique: widen the space before the 4-hex one fills up.
  const wideIds = newTradersEnd * days > 30_000;
  const idSpace = wideIds ? 0x1000000 : 0x10000;
  const idWidth = wideIds ? 6 : 4;
  const asOfMs = Date.parse(`${asOf}T00:00:00Z`);
  const dates = Array.from({ length: days }, (_, i) => isoDate(asOfMs - (days - 1 - i) * DAY_MS));
  const zeros = () => new Array<number>(days).fill(0);

  const revenue = challengePackages.map(zeros);
  const purchases = challengePackages.map(zeros);
  const newTraders = zeros();
  const openChallengeDiff = zeros();
  const openChallengeCapitalDiff = new Array<number>(days + 1).fill(0);
  const fundedDiff = new Array<number>(days + 1).fill(0);
  const fundedCapitalDiff = new Array<number>(days + 1).fill(0);
  const passes = zeros();
  const breachDaily = zeros();
  const breachMax = zeros();
  const rebuysByDay: number[][] = Array.from({ length: days }, () => []);
  const accountIntervals: { trader: number; start: number; end: number }[] = [];
  const payouts: Payout[] = [];

  const traderIds: string[] = [];
  const usedIds = new Set<string>();
  function newTraderId(): number {
    let id = "";
    do {
      id = `T-${Math.floor(rng() * idSpace).toString(16).toUpperCase().padStart(idWidth, "0")}`;
    } while (usedIds.has(id));
    usedIds.add(id);
    traderIds.push(id);
    return traderIds.length - 1;
  }

  function scheduleRebuy(trader: number, fromDay: number) {
    const day = fromDay + geometric(rng, 1 / 3) - 1;
    if (day < days) rebuysByDay[day].push(trader);
  }

  function addDiff(diff: number[], start: number, end: number, value: number) {
    if (start >= days) return;
    diff[start] += value;
    if (end < days) diff[end] -= value;
  }

  function purchase(day: number, trader: number, rebuy: boolean) {
    const index = pickWeighted(rng, [...MODEL.packageWeights]);
    const plan = challengePackages[index];
    revenue[index][day] += rebuy ? plan.rebuyFee : plan.fee;
    purchases[index][day] += 1;

    const challengeEnd = day + Math.min(geometric(rng, 1 / MODEL.meanChallengeDays), 120);
    addDiff(openChallengeDiff, day, challengeEnd, 1);
    addDiff(openChallengeCapitalDiff, day, challengeEnd, plan.accountSize);

    const passed = rng() < MODEL.passProbability;
    const dailyBreach = rng() < MODEL.dailyBreachShare;

    if (!passed) {
      accountIntervals.push({ trader, start: day, end: challengeEnd });
      if (challengeEnd < days) {
        (dailyBreach ? breachDaily : breachMax)[challengeEnd] += 1;
        if (rng() < MODEL.challengeRebuyProbability) scheduleRebuy(trader, challengeEnd);
      }
      return;
    }

    if (challengeEnd < days) passes[challengeEnd] += 1;
    const fundedStart = challengeEnd;
    const fundedEnd = fundedStart + geometric(rng, MODEL.fundedDailyBreachProbability);
    accountIntervals.push({ trader, start: day, end: fundedEnd });
    addDiff(fundedDiff, fundedStart, fundedEnd, 1);
    addDiff(fundedCapitalDiff, fundedStart, fundedEnd, plan.accountSize);

    let requestDay = fundedStart + geometric(rng, 1 / MODEL.meanDaysBetweenPayouts);
    while (requestDay < fundedEnd && requestDay < days) {
      if (rng() < MODEL.payoutRequestProbability) {
        const range = rng() < MODEL.largePayoutProbability ? MODEL.largePayoutProfitRange : MODEL.payoutProfitRange;
        const profit = Math.max(MIN_PAYOUT_USD, Math.round(plan.accountSize * uniform(rng, range[0], range[1])));
        const cents = Math.round(profit * 100 * TRADER_SPLIT_PCT);
        const requestHour = Math.floor(uniform(rng, 0, 24));
        const paidHour = 13 + Math.floor(uniform(rng, 0, 5));
        payouts.push({
          id: `P-${payouts.length + 1}`,
          requestDay,
          paidDay: requestDay + PAYOUT_REVIEW_DAYS,
          requestedOn: isoDate(asOfMs - (days - 1 - requestDay) * DAY_MS),
          paidOn: isoDate(asOfMs - (days - 1 - requestDay - PAYOUT_REVIEW_DAYS) * DAY_MS),
          traderId: traderIds[trader],
          profit,
          cents,
          amount: cents / 100,
          hoursToPay: PAYOUT_REVIEW_DAYS * 24 + paidHour - requestHour,
          txHash: null,
          voided: rng() < MODEL.voidedProbability,
        });
        // No second request while one is under review.
        requestDay += PAYOUT_REVIEW_DAYS;
      }
      requestDay += geometric(rng, 1 / MODEL.meanDaysBetweenPayouts);
    }

    if (fundedEnd < days && rng() < MODEL.fundedRebuyProbability) scheduleRebuy(trader, fundedEnd);
  }

  for (let day = 0; day < days; day += 1) {
    const progress = days > 1 ? day / (days - 1) : 1;
    const weekday = new Date(asOfMs - (days - 1 - day) * DAY_MS).getUTCDay();
    const weekendFactor = weekday === 0 || weekday === 6 ? 0.8 : 1;
    const lambda = (newTradersStart + (newTradersEnd - newTradersStart) * progress ** 1.1) * weekendFactor * uniform(rng, 0.85, 1.15);
    const count = poisson(rng, lambda);
    newTraders[day] = count;
    for (let i = 0; i < count; i += 1) purchase(day, newTraderId(), false);
    for (const trader of rebuysByDay[day]) purchase(day, trader, true);
  }

  /* ---- aggregate series ---- */
  const revenueDaily = dates.map((_, d) => revenue.reduce((sum, row) => sum + row[d], 0));
  const openChallenges = runningFromDiff(openChallengeDiff);
  const openChallengeCapital = runningFromDiff(openChallengeCapitalDiff).slice(0, days);
  const fundedTraders = runningFromDiff(fundedDiff).slice(0, days);
  const fundedCapital = runningFromDiff(fundedCapitalDiff).slice(0, days);
  const activeTraders = openChallenges.map((value, d) => value + fundedTraders[d]);

  const cumPasses = runningFromDiff(passes);
  const cumResolved = runningFromDiff(passes.map((value, d) => value + breachDaily[d] + breachMax[d]));
  const passRate = cumPasses.map((value, d) => (cumResolved[d] >= MODEL.minResolvedForPassRate ? value / cumResolved[d] : null));

  const paid = payouts.filter((payout) => payout.paidDay < days && !payout.voided);
  const payoutCentsDaily = zeros();
  for (const payout of paid) payoutCentsDaily[payout.paidDay] += payout.cents;
  const payoutsDaily = payoutCentsDaily.map((cents) => cents / 100);
  const payoutsCumulative = cumulative(payoutsDaily);

  const notionalVolume = zeros();
  const tradeCount = zeros();
  const volumeByAssetClass = Object.fromEntries(ASSET_CLASSES.map((name) => [name, zeros()])) as Record<AssetClass, number[]>;
  const hedgingRealizedDaily = zeros();
  const hedgingUnrealized = zeros();
  let unrealized = 0;

  for (let d = 0; d < days; d += 1) {
    const weekday = new Date(asOfMs - (days - 1 - d) * DAY_MS).getUTCDay();
    const weekend = weekday === 0 || weekday === 6;
    const capital = openChallengeCapital[d] + fundedCapital[d];
    const volume = Math.round(capital * uniform(rng, 1.1, 1.9) * (weekend ? 0.55 : 1));
    notionalVolume[d] = volume;
    tradeCount[d] = Math.round(activeTraders[d] * uniform(rng, 4.5, 7.5) * (weekend ? 0.6 : 1));

    const base = weekday === 6 ? [0, 1, 0, 0] : weekday === 0 ? [0.08, 0.92, 0, 0] : [0.36, 0.3, 0.22, 0.12].map((share) => share * uniform(rng, 0.85, 1.15));
    const total = base.reduce((sum, share) => sum + share, 0);
    let allocated = 0;
    ASSET_CLASSES.forEach((name, i) => {
      const part = i === ASSET_CLASSES.length - 1 ? volume - allocated : Math.round((volume * base[i]) / total);
      volumeByAssetClass[name][d] = part;
      allocated += part;
    });

    hedgingRealizedDaily[d] = round2(payoutsDaily[d] * uniform(rng, 0.35, 1) + gaussian(rng) * 0.00004 * fundedCapital[d]);
    unrealized = 0.85 * unrealized + gaussian(rng) * 0.0006 * fundedCapital[d];
    hedgingUnrealized[d] = Math.round(unrealized);
  }
  const hedgingRealizedCumulative = cumulative(hedgingRealizedDaily);

  const revenueByPackage: Record<string, number[]> = {};
  const purchasesByPackage: Record<string, number[]> = {};
  challengePackages.forEach((plan, i) => {
    revenueByPackage[plan.id] = revenue[i];
    purchasesByPackage[plan.id] = purchases[i];
  });

  /* ---- stats ---- */
  const feeRevenueLifetime = revenueDaily.reduce((sum, value) => sum + value, 0);
  const last30 = revenueDaily.slice(-30).reduce((sum, value) => sum + value, 0);
  const totalPayoutCents = paid.reduce((sum, payout) => sum + payout.cents, 0);
  const totalPayouts = totalPayoutCents / 100;
  const windowStart = days - 30;
  const active30 = new Set(accountIntervals.filter((item) => item.start < days && item.end > windowStart).map((item) => item.trader));
  const hedgingRealized = hedgingRealizedCumulative[days - 1] ?? 0;
  const resolvedChallenges = cumResolved[days - 1] ?? 0;
  const passCount = cumPasses[days - 1] ?? 0;

  const stats: TransparencyStats = {
    feeRevenueLifetime,
    annualizedRunRate: Math.round((last30 * 365) / 30),
    totalPayouts,
    payoutCount: paid.length,
    largestPayout: paid.reduce((max, payout) => Math.max(max, payout.amount), 0),
    medianHoursToPay: median(paid.map((payout) => payout.hoursToPay)),
    activeTraders30d: active30.size,
    payingTraders: newTraders.reduce((sum, value) => sum + value, 0),
    fundedTraders: fundedTraders[days - 1] ?? 0,
    fundedCapital: fundedCapital[days - 1] ?? 0,
    passRate: resolvedChallenges ? passCount / resolvedChallenges : 0,
    passes: passCount,
    resolvedChallenges,
    challengesSold: purchases.reduce((sum, row) => sum + row.reduce((a, b) => a + b, 0), 0),
    payoutsShareOfRevenue: feeRevenueLifetime ? totalPayouts / feeRevenueLifetime : 0,
    hedgingRealized,
    hedgingUnrealized: hedgingUnrealized[days - 1] ?? 0,
    hedgingCoverage: totalPayouts ? hedgingRealized / totalPayouts : 0,
  };

  const recentPayouts = [...paid]
    .sort((a, b) => b.paidDay - a.paidDay || b.hoursToPay - a.hoursToPay)
    .slice(0, 12)
    .map(({ requestDay: _r, paidDay: _p, cents: _c, voided: _v, ...rest }) => rest);

  return {
    mode: "sample",
    asOf,
    dates,
    packages: challengePackages.map(({ id, name, label }) => ({ id, name, label })),
    series: {
      activeTraders,
      payingTraders: runningFromDiff(newTraders),
      revenueByPackage,
      revenueDaily,
      revenueCumulative: cumulative(revenueDaily),
      purchasesByPackage,
      passRate,
      breachesDaily: breachDaily,
      breachesMax: breachMax,
      notionalVolume,
      tradeCount,
      volumeByAssetClass,
      fundedTraders,
      fundedCapital,
      payoutsDaily,
      payoutsCumulative,
      hedgingRealizedCumulative,
      hedgingUnrealized,
    },
    stats,
    recentPayouts,
  };
}

const cached = new Map<TransparencyScale, TransparencyData>();

/**
 * Build mode: the deterministic sample dataset, at one of three sizes
 * (`medium` is the default). Swap for a live fetch with the same shape.
 */
export function getTransparencyData(scale: TransparencyScale = "medium"): TransparencyData {
  let data = cached.get(scale);
  if (!data) {
    data = buildSampleTransparencyData({ scale });
    cached.set(scale, data);
  }
  return data;
}
